{
 "title": "otus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "latency app",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(app_request_latency_seconds_seconds_bucket{exported_endpoint=\"/app/user\"}[2m])))*1000 ",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(app_request_latency_seconds_seconds_bucket{exported_endpoint=\"/app/user\"}[2m])))*1000 ",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(app_request_latency_seconds_seconds_bucket{exported_endpoint=\"/app/user\"}[2m])))*1000 ",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by (le) (rate(app_request_latency_seconds_seconds_bucket{exported_endpoint=\"/app/user\"}[2m])))*1000 ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Nginx latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])))*1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])))*1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])))*1000",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])))*1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Error Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_bucket{status!~\"2.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Error  App",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_count_total{http_status!~\"2.*\"}[2m])"
    }
   ]
  },
  {
   "title": "RPS Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_bucket [2m]))"
    }
   ]
  },
  {
   "title": "Rps App",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count_total[2m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"default\", container!=\"POD\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\",  container!=\"POD\", container!=\"\"}) by (pod)"
    }
   ]
  }
 ]
}